/**
 * Central export point for all type definitions
 * Import types from here throughout the engine
 */

// Common types
export type {
  Vector2D,
  RGBColor,
  RGBAColor,
  Bounds,
  CircleBounds,
  Point,
  Size,
  Transform,
  Callback,
  CallbackWithParams,
  AsyncCallback,
  Color,
  GameState,
  Alignment,
  Direction,
  EasingFunction,
  Layer,
  SpriteFrame,
  Animation,
  TimerConfig,
  TweenConfig,
  AssetType,
  AssetMetadata,
  Viewport,
  KeyCode,
  MouseButton,
  TouchPoint,
} from "./common.js";

// Entity types
export type {
  Entity,
  ShapeFeatures,
  ShapeOptions,
  RectOptions,
  CircleOptions,
  TriangleOptions,
  TextOptions,
  SpriteOptions,
  PhysicsBody,
  ColliderType,
  Collider,
  TransformEntity,
  PhysicsEntity,
  AnimatedSpriteData,
  ParticleData,
  Component,
  ComponentEntity,
} from "./entities.js";

// System types
export type {
  PhysicsConfig,
  PhysicsObject,
  CollisionConfig,
  CollisionRect,
  CollisionCircle,
  CollisionResult,
  RenderConfig,
  CameraConfig,
  CameraTarget,
  ParallaxLayer,
  ParticleSystemConfig,
  ParticleConfig,
  ExplosionData,
  InputConfig,
  InputState,
  DragConfig,
  Draggable,
  AudioConfig,
  SoundOptions,
  SceneConfig,
  GameLoopConfig,
  CanvasConfig,
  AssetLoaderConfig,
  GraphicsCacheConfig,
  GradientType,
  PatternRepetition,
  GradientColorStop,
  LinearGradientCoordinates,
  RadialGradientCoordinates,
  TransformMatrix,
  SceneManagerConfig,
} from "./systems.js";
